### ISSUE TITLE
match ?

### ISSUE THREAD

**Issue by Cottin** [plaid/sanctuary#28]
Would it make sense to add a `match` function?

```
R.head(R.match(/xxx/, 'abcde')) // returns TypeError: Cannot read property '0' of null
```
http://bit.ly/1HasPS6

We'd be "safer" with something like
```
smatch = curry (re, s) ->
	res = R.match re, s
	return if res then Just(res) else Nothing()
```

Would it make sense to just add "safe" versions of all functions in Ramda that might otherwise need null checks? Is there some smart generic way to wrap Ramda functions and make them return `Maybe`s instead?

**Comment by davidchambers** [comment]
> Would it make sense to just add "safe" versions of all functions in Ramda that might otherwise need null checks?

Yes, I think so!

> Is there some smart generic way to wrap Ramda functions and make them return `Maybe`s instead?

Good question. In the case of [`R.match`][1], composing with `S.toMaybe` should do the trick. `S.find` can't be defined in terms of [`R.find`][2], though, since `S.find(R.eq(undefined), [undefined])` should return a Just while `S.find(R.eq(undefined), [])` should return a Nothing.


[1]: http://ramdajs.com/docs/#match
[2]: http://ramdajs.com/docs/#find
