### ISSUE TITLE
integer type

### ISSUE THREAD

**Issue by davidchambers** [plaid/sanctuary#45]
This may or may not be useful:

```javascript
> S.Int(7).add(S.Int(2))
Int(9)
> S.Int(7).divideBy(S.Int(2))
Int(3)
> S.Int(7).valueOf()
7
```

An integer type would allow us to specify types more precisely. [`S.at`][1], for example, could have type `Int -> [a] -> Maybe a`.

[1]: https://github.com/plaid/sanctuary#at

**Comment by paldepind** [comment]
There is a tricky thing though. Numbers can be an instance of monoids in two different ways.

You could do either of these:

```javascript
Int.prototype.empty = function() { Int(0); };
Int.prototype.concat = function(other) {
  return Int(this.valueOf() + other.valueOf());
};
```
```javascript
Int.prototype.empty = function() { Int(1); };
Int.prototype.concat = function(other) {
  return Int(this.valueOf() * other.valueOf());
};
```

**Comment by davidchambers** [comment]
> Numbers can be an instance of monoids in two different ways.

True. I don't think this should prevent us from supporting one of the two. There are, I believe, multiple lawful definitions of [`Either#concat`][1]. @joneshf and I chose the one which seemed most useful, but I recall @CrossEye advocating a different definition.

> To be honest I think using a integer type would be too much bother because you loose the ability to use operators.

That's not *quite* true, since one can define `Int#valueOf :: Int ~> Number`:

```javascript
> S.Int(1) + S.Int(2)
3
```

To get `Int(3)` as the result one would use `S.add` (or `R.add` if it is updated to dispatch to `add`).

I use operators infrequently. I use `R.add`, `R.inc`, etc. in many places. Switching to polymorphic versions of these functions would be straightforward.

> It is also much less typing to just use a literal.

I'm happy to pay this price in order to have more accurate types. [`S.parseInt`][2], for example, would become:

    parseInt :: Int -> String -> Maybe Int

A radix of `2.5` is nonsensical. Having the run-time type checker reject such values would be very nice indeed.

> Have you considered hacking support for numbers into various places instead? So that one could do this for instance:
>
> ```javascript
> S.Just(4).concat(S.Just(12)); => Just(16)
> ```

I see this as orthogonal to the question of an Int type. I very much like the idea of a `concat` function which performs addition on Number arguments. It could *also* be defined for Int arguments:

```javascript
> S.Just(S.Int(4)).concat(S.Just(S.Int(12)))
Just(Int(16))
```


[1]: https://github.com/plaid/sanctuary#Either.prototype.concat
[2]: https://github.com/plaid/sanctuary#parseInt

**Comment by CrossEye** [comment]
I would be concerned about defining `concat` as `add`.  The minute you do, you'll want it to mean something else.  

I don't think there is much of a reason to try to define standard Monoids on numeric types.  One can create an Add monoid and a Multiply monoid over a numeric type if necessary, or even more esoteric ones, but I think simply defining the operators you want would be more useful.  This would be great if it worked:

```js
    add(Just(4), Just(12)); //=> Just(16)
    multiply(Just(6), Just(7)); //=> Just(42)
```

Of course that won't work so simply.  But the missing step is not that hard:

```js
    lift(add)(Just(4), Just(12)); //=> Just(16)
    lift(multiply)(Just(6), Just(7)); //=> Just(42)
```

I don't have any strong opinions on Sanctuary adding an `Int` type.  I would hesitate to require it in API locations that now look for an integer input though, especially if the main goal is to delegate the validation of inputs to a type-checker.  Because pretty soon you're going to find the case where you then want the `PositiveInteger`, `NonNegativeInteger`, and `EvenInteger` types to handle other validations; and soon after that it will be `NonNegativeEvenInteger` and `OddIntegerLessThan100`, or some such.  It'll be a beautiful hierarchy.

Such constraints are much better written as predicates than as types.

**Comment by paldepind** [comment]
> That's not quite true, since one can define Int#valueOf :: Int ~> Number:

Yes. But that is quite awkward since the result of the addition is of a different type. That does not seem well behaved to me: `(+) :: Int -> Int -> Number`.

> I'm happy to pay this price in order to have more accurate types. S.parseInt, for example, would become:

I don't really understand why you think having an explicit integer type is necessary for that. What's in the way of just using that type today anyway? [JavaScript has the concept that a number can be an integer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger). I very much agree with @CrossEye's concern and will merely add that having to type and read `S.at(Int(3), list)` seems awkward.

> I see this as orthogonal to the question of an Int type.

Yes. You can definitely see them as orthogonal. But my point was that Sanctuary functions could in general treat numbers as being instances of their respective type classes in all relevant cases and thus one wouldn't need to have an `Int` object in order to achieve that.

**Comment by davidchambers** [comment]
> But my point was that Sanctuary functions could in general treat numbers as being instances of their respective type classes in all relevant cases and thus one wouldn't need to have an `Int` object in order to achieve that.

Oh, I see your point now (which may also be what @CrossEye was saying). I absolutely :heart: this idea!

I was ready to raise two objections, but in writing them I thought of good solutions to both. :)

__We would lose the ability to provide polymorphic functions.__ For example:

```haskell
divide :: Numeric n => n -> n -> Maybe n
```

Should `divide(7, 2)` evaluate to `3` or `3.5`? It's ambiguous. We'd need separate functions:

```haskell
divide :: Number -> Number -> Maybe Number
divideInt :: Int -> Int -> Maybe Int
```

This seems fine, though, since we could use `S.Int` as a namespace for Int-specific functions (and `S.Float` for Float-specific functions potentially). Actually, this solves another problem I'd encountered. I'd like to provide the following functions:

```haskell
and :: Int -> Int -> Int
or  :: Int -> Int -> Int
xor :: Int -> Int -> Int
```

These would be function equivalents of JavaScript's `&`, `|`, and `^` operators. The problem is that Sanctuary already defines functions with these names, and we should avoid having these functions mean two very different things.

__We would need more manual bounds detection.__ Currently, `add` simply returns `Int(a + b)`. This will result in a run-time type error if the result of adding `a` and `b` is beyond the bounds of a signed 32-bit integer (32-bit since I'd like to provide the bitwise functions).

Actually, now that I think about it this needn't be an issue. We could define `Int` as follows:

```javascript
var Int = function(n) {
  if (R.is(Number, n) && (n | 0) === Number(n)) {
    return n;
  } else {
    throw new TypeError(R.toString(n) + ' is not a 32-bit integer');
  }
};
```

It wouldn't create a container, it would simply ensure that the given value is a Number representing an integer within the bounds.
